"""
flow.py – Workflow phase and step definitions.

Sprint Zero artifact chain
──────────────────────────
  Step 1 – conduct_requirements_interview
    Agent : InterviewerAgent ↔ EndUserAgent
    Input : (none)
    Output: interview_record

    InterviewerAgent calls update_requirements after EVERY stakeholder turn.
    Each requirement carries a ``rationale`` field — a structured 4-section synthesis
    generated by a dedicated mini-LLM call (STAKEHOLDER EVIDENCE / INFERENCE /
    REQUIREMENT BASIS / CONFIDENCE).
    Conflicts are resolved INLINE via Socratic follow-up.
    Stops when interview_complete=True (three-tier judgment) or max_turns.

  Step 2 – review_interview_record          ← human-in-the-loop gate
    Agent : human reviewer (LangGraph interrupt)
    Input : interview_record
    Output: reviewed_interview_record

    Two outcomes:
      • Approved  → reviewed_interview_record artifact written; flow → step 3.
      • Rejected  → interview_record removed; review_feedback injected; → step 1.

  Step 3 – build_product_backlog_draft       ← NEW: draft before analyst
    Agent : SprintAgent (Pipeline A-Draft)
    Input : reviewed_interview_record
    Output: product_backlog_draft

    SprintAgent scores Fibonacci story points and WSJF ranks.
    INVEST evaluation is intentionally DEFERRED to AnalystAgent in step 4.
    The requirement rationale is injected into the task prompt so SprintAgent
    can cross-reference stakeholder intent during estimation.

  Step 4 – analyst_review                   ← NEW: INVEST + NLP quality gate
    Agent : AnalystAgent
    Input : product_backlog_draft + (reviewed_interview_record for rationale)
    Output: analyst_feedback

    AnalystAgent applies INVEST criteria per PBI, detects vague terms, assesses
    duplicate risk, and cross-checks descriptions against requirement rationale.
    Writes a structured analyst_feedback artifact without modifying the draft.

  Step 5 – refine_product_backlog            ← NEW: apply analyst feedback → final
    Agent : SprintAgent (Pipeline A-Refine)
    Input : product_backlog_draft + analyst_feedback
    Output: product_backlog

    SprintAgent reads every analyst recommendation and applies revisions:
    rewrites, acceptance criteria, story splits, story-point adjustments.
    May override analyst suggestions when requirement rationale supports the
    original description.  Writes the publication-quality product_backlog artifact.

Design rationale (three-artifact A-pipeline)
─────────────────────────────────────────────
Separating estimation (step 3) from quality-gating (step 4) and refinement (step 5)
gives each agent a single, focused responsibility.  The draft artifact provides
a clean before/after record:
  product_backlog_draft  — pre-analyst raw estimation
  analyst_feedback       — INVEST + NLP review log (permanent audit trail)
  product_backlog        — post-analyst refined, publication-quality backlog

The full requirement rationale (generated by InterviewerAgent's mini-LLM synthesis)
flows through all three steps so every estimation and quality decision is traceable
back to the original stakeholder conversation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


@dataclass
class ArtifactStep:
    step_name:          str
    node_name:          str
    requires_artifacts: List[str]
    produces_artifact:  str
    agent_name:         str
    description:        str = ""


@dataclass
class PhaseDefinition:
    phase_name:   str
    display_name: str
    description:  str
    steps:        List[ArtifactStep]
    next_phase:   Optional[str] = None


WORKFLOW_PHASES: List[PhaseDefinition] = [

    PhaseDefinition(
        phase_name="sprint_zero_planning",
        display_name="Sprint Zero — Discovery & Planning",
        description=(
            "Gather software requirements via stakeholder interviews "
            "(with live, conflict-aware incremental extraction and structured "
            "mini-LLM rationale synthesis), submit the interview record for human "
            "review, build an initial backlog draft, run an independent INVEST + NLP "
            "analyst review, apply feedback to produce the final backlog."
        ),
        steps=[
            ArtifactStep(
                step_name="conduct_requirements_interview",
                node_name="interviewer_turn",
                requires_artifacts=[],
                produces_artifact="interview_record",
                agent_name="interviewer",
                description=(
                    "InterviewerAgent conducts a multi-turn dialogue. "
                    "After EACH stakeholder reply, calls update_requirements which "
                    "invokes a mini-LLM to generate a 4-section structured rationale "
                    "(STAKEHOLDER EVIDENCE / INFERENCE / REQUIREMENT BASIS / CONFIDENCE). "
                    "Conflicts trigger inline Socratic clarification. "
                    "Stops when completeness ≥ threshold (interview_complete=True) "
                    "or max_turns safety net."
                ),
            ),

            ArtifactStep(
                step_name="review_interview_record",
                node_name="review_turn",
                requires_artifacts=["interview_record"],
                produces_artifact="reviewed_interview_record",
                agent_name="human_reviewer",
                description=(
                    "Human reviewer inspects every requirement together with its "
                    "structured rationale and modification history. "
                    "• Approved  → reviewed_interview_record artifact written. "
                    "• Rejected  → interview_record removed; review_feedback injected; "
                    "  flow returns to conduct_requirements_interview."
                ),
            ),

            ArtifactStep(
                step_name="build_product_backlog_draft",
                node_name="sprint_agent_turn",
                requires_artifacts=["reviewed_interview_record"],
                produces_artifact="product_backlog_draft",
                agent_name="sprint_agent",
                description=(
                    "SprintAgent (Pipeline A-Draft) reads reviewed_interview_record "
                    "(including structured requirement rationale) and produces the "
                    "initial product_backlog_draft with Fibonacci estimation and WSJF "
                    "prioritisation. INVEST evaluation is deferred to AnalystAgent."
                ),
            ),

            # ── NEW: Analyst INVEST + NLP review ──────────────────────────
            ArtifactStep(
                step_name="analyst_review",
                node_name="analyst_turn",
                requires_artifacts=["product_backlog_draft"],
                produces_artifact="analyst_feedback",
                agent_name="analyst",
                description=(
                    "AnalystAgent reads product_backlog_draft and the requirement "
                    "rationale table from reviewed_interview_record, then performs: "
                    "• INVEST criterion evaluation (all 6 criteria, per PBI). "
                    "• Vague-term detection (NLP). "
                    "• Duplicate risk assessment (Jaccard similarity). "
                    "• Rationale alignment check (valuable/testable cross-check). "
                    "Writes analyst_feedback artifact — does NOT modify the draft."
                ),
            ),

            # ── NEW: SprintAgent applies feedback → final backlog ──────────
            ArtifactStep(
                step_name="refine_product_backlog",
                node_name="sprint_agent_turn",
                requires_artifacts=["product_backlog_draft", "analyst_feedback"],
                produces_artifact="product_backlog",
                agent_name="sprint_agent",
                description=(
                    "SprintAgent (Pipeline A-Refine) reads analyst_feedback and "
                    "applies per-PBI revisions: rewrites, acceptance criteria, "
                    "story splits, story-point adjustments. May override analyst "
                    "suggestions when requirement rationale supports the original "
                    "description. Writes the final product_backlog artifact."
                ),
            ),
        ],
        next_phase="sprint_execution",
    ),

    PhaseDefinition(
        phase_name="sprint_execution",
        display_name="Sprint N — Execution",
        description="Iterative sprint cycles.",
        steps=[],
        next_phase="sprint_review",
    ),

    PhaseDefinition(
        phase_name="sprint_review",
        display_name="Sprint Review & Retrospective",
        description="Evaluate sprint outcomes and retrospective.",
        steps=[],
        next_phase=None,
    ),
]

PHASE_INDEX: Dict[str, PhaseDefinition] = {p.phase_name: p for p in WORKFLOW_PHASES}
PHASE_ORDER: List[str] = [p.phase_name for p in WORKFLOW_PHASES]


def get_next_action(
    artifacts: Dict,
    current_phase: Optional[str] = None,
) -> Optional[Tuple[str, str, str]]:
    """Return (phase_name, step_name, node_name) for the next incomplete step,
    or None if all phases are complete.

    Scans from current_phase onward.  For each step, checks:
      • All required_artifacts are present  (prerequisites met)
      • The produced artifact is absent     (step not yet done)
    Returns the first matching step.
    """
    start_idx = 0
    if current_phase and current_phase in PHASE_INDEX:
        try:
            start_idx = PHASE_ORDER.index(current_phase)
        except ValueError:
            start_idx = 0

    for i in range(start_idx, len(WORKFLOW_PHASES)):
        phase = WORKFLOW_PHASES[i]
        for step in phase.steps:
            reqs_met = all(r in artifacts for r in step.requires_artifacts)
            not_done = step.produces_artifact not in artifacts
            if reqs_met and not_done:
                return phase.phase_name, step.step_name, step.node_name

    return None