"""
state.py

WorkflowState – single source of truth flowing through the LangGraph graph.
analyst_feedback schema added for AnalystAgent review loop.

Requirements rationale is now a structured 4-section synthesis generated by
a dedicated mini-LLM call inside _tool_update_requirements (see interviewer.py).

analyst_feedback schema
───────────────────────
  {
    "session_id":             "<str>",
    "reviewed_artifact":      "product_backlog_draft",
    "overall_quality_score":  <float 0.0–1.0>,
    "critical_issues":        <int>,
    "pbi_reviews":            [
      {
        "pbi_id":        "PBI-001",
        "source_req_id": "FR-001",
        "severity":      "high" | "medium" | "low" | "pass",
        "vague_terms":   ["fast", ...],
        "invest_check":  {
          "independent": {"pass": bool, "note": str},
          "negotiable":  {"pass": bool, "note": str},
          "valuable":    {"pass": bool, "note": str},
          "estimable":   {"pass": bool, "note": str},
          "small":       {"pass": bool, "note": str},
          "testable":    {"pass": bool, "note": str},
        },
        "duplicate_risk":    "high" | "medium" | "low",
        "recommendations":   ["<action>", ...],
        "thought":           "<analyst reasoning>",
      }, ...
    ],
    "recommendations_summary": "<overall>",
    "notes":                   "<analyst conclusion>",
    "created_at":              "<ISO timestamp>",
  }
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class SystemPhase(str, Enum):
    SPRINT_ZERO_PLANNING = "sprint_zero_planning"
    SPRINT_EXECUTION     = "sprint_execution"
    SPRINT_REVIEW        = "sprint_review"


class ProcessPhase(str, Enum):
    ELICITATION   = "elicitation"
    ANALYSIS      = "analysis"
    SPECIFICATION = "specification"
    VALIDATION    = "validation"


class ConversationTurn(TypedDict):
    role:      str   # "interviewer" | "enduser"
    content:   str
    timestamp: str


class WorkflowState(TypedDict, total=False):

    # ── Session ────────────────────────────────────────────────────────────
    session_id:          str
    project_description: str

    # ── Phase management ───────────────────────────────────────────────────
    system_phase: str

    # ── Artifact store ─────────────────────────────────────────────────────
    artifacts:    Dict[str, Any]
    artifact_ids: Dict[str, str]

    # ── Supervisor routing ─────────────────────────────────────────────────
    next_node: str

    # ── Interview sub-state ────────────────────────────────────────────────
    conversation:       List[ConversationTurn]
    turn_count:         int
    max_turns:          int
    interview_complete: bool   # set True ONLY by InterviewerAgent

    # ── Requirements draft ─────────────────────────────────────────────────
    # Each rationale is a structured mini-LLM synthesis (4 sections):
    #   STAKEHOLDER EVIDENCE / INFERENCE / REQUIREMENT BASIS / CONFIDENCE
    requirements_draft: List[Dict[str, Any]]

    # ── Coverage map ───────────────────────────────────────────────────────
    coverage_map: Dict[str, Any]

    # ── Goal tracker (Tier-2 stopping) ─────────────────────────────────────
    goal_tracker: Dict[str, Any]

    # ── Conflict and dependency logs ───────────────────────────────────────
    conflict_log:     List[Dict[str, Any]]
    dependency_graph: Dict[str, Any]

    # ── Backlog drafts ─────────────────────────────────────────────────────
    # backlog_draft: shared working list for Pipeline A-Draft and A-Refine.
    backlog_draft: List[Dict[str, Any]]
    sprint_draft:  List[Dict[str, Any]]

    # ── HITL review gate ───────────────────────────────────────────────────
    awaiting_review:  bool
    review_approved:  bool
    review_feedback:  Optional[str]

    # ── Analyst feedback ───────────────────────────────────────────────────
    # Written by AnalystAgent into artifacts["analyst_feedback"].
    analyst_feedback: Dict[str, Any]

    # ── ReAct internals (transient) ────────────────────────────────────────
    _last_react_thought: str
    _react_strategy:     str

    # ── Error accumulation ─────────────────────────────────────────────────
    errors: List[str]